config/routes.rb
Rails.application.routes.draw do

  get 'admins/index'

  	root 'home#index'
  
	devise_for :users, :controllers => {:registrations => "users/registrations"}
	# resources :users
	# match 'users/:id', to: 'users/users#show', via: [:get, :post]
	# match 'users/:id', to: 'users/users#index', via: [:get, :post]
	match 'profile/', to: 'users/users#index', via: [:get]
	match 'users/', to: 'users/users#show', via: [:get]

	# match 'users/sign_out' => "devise/sessions#destroy", via: [:delete]
	# delete 'users/sign_out'  => "devise/sessions#destroy"

	# devise_for :users do
	  # delete '/users/sign_out' => 'devise/sessions#destroy'
	# end

	resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 	
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true,
                    length: { minimum: 5 }
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  load_and_authorize_resource

  def index
  	@articles = Article.all
  end

  def new
  	@articles = Article.new
  	authorize! :manage, @article
  end

  def edit
    @article = Article.find(params[:id])
    authorize! :manage, @article
  end

  def show
  	@article = Article.find(params[:id])
  	authorize! :manage, @article
  end

  def create
  	@article = Article.new(article_params)
  	if @article.save
  		redirect_to @article
  	else
      render :new
  	end

  	authorize! :manage, @article
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
    authorize! :manage, @article
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
    authorize! :manage, @article
  end

  private
  def article_params
  	params.require(:article).permit(:title, :content)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<h1>Articles#index</h1>

<% if cannot? :manage, @article %>
	<%= link_to "(login)", new_user_session_path %>
<% end %>

<br>

<table>
	<tr>
		<td class="td1">Title</td>
		<td class="td2">Content</td>
		<% if can? :create, @article %>
		<td class="td3">
			<%=  link_to "Create new article", new_article_path %>
		</td>
		<% end %>
	</tr>

	<% if @articles.count == 0 %>
	<tr>
		<td>...</td>
		<td>...</td>
		<td>...</td>
	</tr>
	<% end %>

	<% @articles.each do |article| %>
	<tr>
		<td>
			<%= article.title %>
		</td>

		<td>
			<%= article.content %>
		</td>

		<% if can? :manage, @article %>		
		<td>
			<%= link_to "show", article_path(article) %>
			<%= link_to "edit", edit_article_path(article) %>
			<%= link_to "delete", article_path(article), method: :delete, data:{ confirm: "Are you sure?"} %>
		</td>
		<% end %>
	</tr>
	<% end %>
</table>

app/views/articles/new.html.erb
<h2>Create new article</h2>

<%= form_for :article, url: articles_path, method: :post do |f| %>  
<%if @article.errors.full_messages.any? %>
  <% @article.errors.full_messages.each do |error_message| %>
    <% puts error_message %>
  <% end %>
<% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit "Create" %>
  </div>
<% end %>

app/views/articles/show.html.erb
<h2>show article</h2>
<span> |(Title:) </span>
<%= @article.title %><br>
<span> |(Content:) </span>
<%= @article.content %><br>
<span>  |(Created_at:) </span>
<%= @article.created_at %><br>
<span>  |(Updated_at:) </span>
<%= @article.updated_at %> <br>
<%= link_to "Back", root_path %>